function executarOperacao() {
    try {
        throw new Error("Erro gen√©rico");
    } catch (erro: unknown) {
        if (erro instanceof Error) {
    console.log("Erro:", erro.message);
    }
    }
}

